package com.medset.medsetai.model;

/**
 * Represents a symptom entered for a simulated patient.
 *
 * <p>The model stores both the original text supplied by the user and the
 * normalized symptom name generated by the language-processing service.
 * This allows the application to preserve the original input while using
 * consistent labels for educational set operations.</p>
 */
public class Symptom {

    /** Unique symptom identifier assigned by SQLite. */
    private long id;

    /** Identifier of the patient associated with this symptom. */
    private long patientId;

    /** Original symptom description entered by the user. */
    private String originalText;

    /** Standardized symptom label, such as "fever" or "cough". */
    private String normalizedName;

    /** Language detected in the original input, such as "es" or "en". */
    private String language;

    /**
     * Creates an empty symptom.
     */
    public Symptom() {
    }

    /**
     * Creates a symptom before it is stored in the database.
     *
     * @param originalText original user-provided text
     * @param normalizedName standardized symptom label
     * @param language detected language code
     */
    public Symptom(
            String originalText,
            String normalizedName,
            String language
    ) {
        this.originalText = originalText;
        this.normalizedName = normalizedName;
        this.language = language;
    }

    /**
     * Creates a symptom with its database and patient identifiers.
     *
     * @param id symptom identifier
     * @param patientId associated patient identifier
     * @param originalText original user-provided text
     * @param normalizedName standardized symptom label
     * @param language detected language code
     */
    public Symptom(
            long id,
            long patientId,
            String originalText,
            String normalizedName,
            String language
    ) {
        this.id = id;
        this.patientId = patientId;
        this.originalText = originalText;
        this.normalizedName = normalizedName;
        this.language = language;
    }

    /**
     * Returns the symptom identifier.
     *
     * @return symptom identifier
     */
    public long getId() {
        return id;
    }

    /**
     * Assigns the symptom identifier.
     *
     * @param id symptom identifier
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Returns the associated patient identifier.
     *
     * @return patient identifier
     */
    public long getPatientId() {
        return patientId;
    }

    /**
     * Assigns the associated patient identifier.
     *
     * @param patientId patient identifier
     */
    public void setPatientId(long patientId) {
        this.patientId = patientId;
    }

    /**
     * Returns the original symptom text.
     *
     * @return original text
     */
    public String getOriginalText() {
        return originalText;
    }

    /**
     * Updates the original symptom text.
     *
     * @param originalText original text to store
     */
    public void setOriginalText(String originalText) {
        this.originalText = originalText;
    }

    /**
     * Returns the normalized symptom name.
     *
     * @return normalized symptom label
     */
    public String getNormalizedName() {
        return normalizedName;
    }

    /**
     * Updates the normalized symptom name.
     *
     * @param normalizedName standardized label
     */
    public void setNormalizedName(String normalizedName) {
        this.normalizedName = normalizedName;
    }

    /**
     * Returns the detected language code.
     *
     * @return language code
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Updates the detected language code.
     *
     * @param language language code
     */
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * Returns the normalized name for list displays.
     *
     * @return normalized symptom label
     */
    @Override
    public String toString() {
        return normalizedName;
    }
}